#!/usr/bin/env node
// @effect-diagnostics nodeBuiltinImport:off globalConsole:off - a synchronous codegen step with no Effect runtime to host.
// Embeds infra/hermes (patches.json and every patch version it lists) into the
// server so every build (npm, single executable, desktop) can apply them
// without shipping loose files.
// Run after changing the manifest or a patch: node scripts/generate-hermes-patches.ts
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

const repoRoot = NodePath.resolve(import.meta.dirname, "..");
const sourceDir = NodePath.join(repoRoot, "infra/hermes");
const target = NodePath.join(repoRoot, "apps/server/src/hermes/hermesPatchFiles.generated.ts");

const fail = (message: string): never => {
  console.error(`infra/hermes/patches.json: ${message}`);
  process.exit(1);
};

const isText = (value: unknown): value is string =>
  typeof value === "string" && value.trim().length > 0;

/** Every .patch below infra/hermes, as a manifest-relative path. */
const patchFilesOnDisk = (directory: string): string[] =>
  NodeFS.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = NodePath.join(directory, entry.name);
    if (entry.isDirectory()) return patchFilesOnDisk(full);
    return entry.name.endsWith(".patch")
      ? [NodePath.relative(sourceDir, full).split(NodePath.sep).join("/")]
      : [];
  });

const manifest = JSON.parse(NodeFS.readFileSync(NodePath.join(sourceDir, "patches.json"), "utf8"));
const patches: unknown = manifest?.patches;
if (!Array.isArray(patches) || patches.length === 0) fail("expected a non-empty `patches` array");

const ids = new Set<string>();
const listed = new Set<string>();
const generated = (patches as ReadonlyArray<Record<string, unknown>>).map((patch) => {
  const { id, title, neededFor, versions } = patch;
  if (!isText(id) || !isText(title) || !isText(neededFor)) {
    return fail(`every patch needs an id, title, and neededFor (${JSON.stringify(id)})`);
  }
  if (ids.has(id)) fail(`duplicate patch id ${id}`);
  ids.add(id);
  if (!Array.isArray(versions) || versions.length === 0) fail(`${id} has no versions`);

  let newer = Number.POSITIVE_INFINITY;
  const embedded = (versions as ReadonlyArray<Record<string, unknown>>).map((version) => {
    const { hermesCommit, hermesCommitDate, file } = version;
    if (typeof hermesCommit !== "string" || !/^[0-9a-f]{40}$/.test(hermesCommit)) {
      return fail(`${id}: hermesCommit must be 40 lowercase hex characters`);
    }
    const time = typeof hermesCommitDate === "string" ? Date.parse(hermesCommitDate) : NaN;
    if (
      typeof hermesCommitDate !== "string" ||
      !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(hermesCommitDate) ||
      Number.isNaN(time)
    ) {
      return fail(`${id}: hermesCommitDate must be a UTC time like 2026-10-01T19:37:31Z`);
    }
    if (time > newer) fail(`${id}: versions must be listed newest first`);
    newer = time;
    if (!isText(file) || !NodeFS.existsSync(NodePath.join(sourceDir, file))) {
      return fail(`${id}: missing file ${JSON.stringify(file)}`);
    }
    if (listed.has(file)) fail(`${file} is listed more than once`);
    listed.add(file);
    return {
      hermesCommit,
      hermesCommitDate,
      file,
      content: NodeFS.readFileSync(NodePath.join(sourceDir, file), "utf8"),
    };
  });
  return { id, title, neededFor, versions: embedded };
});

for (const file of patchFilesOnDisk(sourceDir)) {
  if (!listed.has(file)) fail(`${file} is not listed in the manifest`);
}

NodeFS.writeFileSync(
  target,
  [
    "// Generated by scripts/generate-hermes-patches.ts from infra/hermes. Do not edit.",
    "export interface HermesPatchFileVersion {",
    "  /** The Hermes commit this version was made and verified against. */",
    "  readonly hermesCommit: string;",
    "  /** That commit's committer date, in UTC. */",
    "  readonly hermesCommitDate: string;",
    "  /** Path below infra/hermes. */",
    "  readonly file: string;",
    "  /** Patch text, as `git apply` reads it. */",
    "  readonly content: string;",
    "}",
    "",
    "export interface HermesPatchFile {",
    "  readonly id: string;",
    "  readonly title: string;",
    "  readonly neededFor: string;",
    "  /** Newest first. */",
    "  readonly versions: ReadonlyArray<HermesPatchFileVersion>;",
    "}",
    "",
    `export const HERMES_PATCH_FILES: ReadonlyArray<HermesPatchFile> = ${JSON.stringify(generated)};`,
    "",
  ].join("\n"),
);
console.log(
  `Wrote ${generated.length} patch(es), ${listed.size} version(s) to ${NodePath.relative(repoRoot, target)}`,
);
